### ISSUE TITLE
Does this provider support RichText?

### ISSUE THREAD

**Issue by rahulpatel596** [labd/terraform-provider-contentful#34]
Does the provider support richText entries?
I am trying to add this entry but getting validation error. Am I missing something or is RichText not supported?
Thank you so much for assistance

Error message:
`The type of \\\\"value\\\\" is incorrect, expected type: RichText\\",\\"path\\":[\\"fields\\",\\"content\\",\\"en\\"]}]}`

ContentType Field:
```
  field {
    id       = "content"
    name     = "Content"
    type     = "RichText"
  }
```

Entry Field:
```
field {
    id = "content"
    locale = "en"
    content = jsonencode({
      data= [],
      content= [
        {
          nodeType= "paragraph",
          content= [
            {
              nodeType= "text",
              marks= [],
              value= "This is paragraph.",
              data= [],
            },
          ],
          data= [],
        }
      ],
      nodeType= "document"
    })
  }
```

**Comment by rahulpatel596** [comment]
@demeyerthom Would appreciate your input on this

**Comment by rahulpatel596** [comment]
@demeyerthom Sorry for the ping, Do you have any insights on this?
If provider doesn't support Richtext, I can add a PR for it

**Comment by demeyerthom** [comment]
Hi @rahulpatel596!

I ran a quick test with the same entries, and I am getting the same errors. This is because the provider value is an encoded json string (which is the type defined in the provider), but the API actually expects an unencoded json object. 

I will release a fix a bit to attempt unmarshalling the values before sending them to the API.

Sidenote: your json will still fail; the `data` fields should be objects, not arrays. This is enforced by the api from contentful

**Comment by rahulpatel596** [comment]
Appreciate your help on this. Thank you so much @demeyerthom

**Comment by rahulpatel596** [comment]
<img width="749" alt="Screenshot 2024-06-09 at 10 06 57 PM" src="https://github.com/labd/terraform-provider-contentful/assets/33618437/77b2ba95-259e-4f08-9359-aeb5e7bc497e">
@demeyerthom It seems like this version hasn't been deployed in terraform cloud yet.

**Comment by rahulpatel596** [comment]
@demeyerthom Would it be possible to look into above. It looks like github-actions release step is failing.
